# https://hub.docker.com/r/gitlab/gitlab-ce/

replicaCount: 1

image:
  repository: gitlab/gitlab-ce
  tag: 10.8.4-ce.0
  pullPolicy: IfNotPresent

gitlab:
  dbHost: ""
  dbPort: ""
  dbName: gitlab
  dbUsername: gitlab
  dbPassword: gitlab
  externalURL: https://gitlab.example.com
  saml:
    enabled: false
    buttonLabel: Login
    IDPCert: |
      -----BEGIN CERTIFICATE-----
      MII...
      -----END CERTIFICATE-----
    IDPSSOTargetURL: https://idp.example.com

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - gitlab.example.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
  # existingClaim: existing-pvc

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
