apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nextcloud.fullname" . }}
  labels:
    app: {{ template "nextcloud.name" . }}
    chart: {{ template "nextcloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.adminPassword }}
  adminPassword: {{ .Values.adminPassword | b64enc | quote }}
{{- else  }}
  adminPassword: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}
{{- if .Values.externalDatabase.password }}
  externalDatabasePassword: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
