# https://hub.docker.com/r/mattermost/mattermost-prod-app/

replicaCount: 1

image:
  repository: mattermost/mattermost-prod-app
  tag: 4.10.1
  pullPolicy: IfNotPresent

mattermost:
  dbHost: ""
  dbPort: ""
  dbName: mattermost
  dbUsername: mattermost
  dbPassword: mattermost

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - mattermost.example.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
  # existingClaim: existing-pvc

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
