# https://github.com/cptactionhank/docker-atlassian-jira-software

image:
  repository: cptactionhank/atlassian-jira-software
  tag: 7.10.1
  pullPolicy: IfNotPresent

jira:
  reverseProxyHost: jira.cenoq.com
  reverseProxyPort: 80
  reverseProxyScheme: http
  javaHeapSize: 4096m
  javaMemoryOptions: "-XX:MaxMetaspaceSize=512m -XX:MaxDirectMemorySize=10m"
  javaOptions: ""

service:
  type: LoadBalancer  #ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - jira.cenoq.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
  # existingClaim: existing-pvc

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
